#include "IO.h"
#include <stdio.h>
#include <stdlib.h>

/**
 * Allocate memory and load the input data.
 *
 * Files should be the output generated by matrixgen.c
 *
 * @param A Pointer for where Matrix A will be stored
 * @param B Pointer for where Matrix B will be stored
 * @param n Pointer to matrix size
 *
 * @return Error code, 0 for OK, anything otherwise
 */
int LoadInput(int ***A, int ***B, int *n) {

    FILE *ip;
    int i, j;

    if ((ip = fopen("data_input", "r")) == NULL) {
        printf("error opening the input data.\n");
        return 1;
    }
    fscanf(ip, "%d\n", n);

    *A = malloc(*n * sizeof(int *));
    *B = malloc(*n * sizeof(int *));

    for (i = 0; i < *n; i++) {
        (*A)[i] = malloc(*n * sizeof(int));
        (*B)[i] = malloc(*n * sizeof(int));
    }

    for (i = 0; i < *n; i++)
        for (j = 0; j < *n; j++)
            fscanf(ip, "%d\t", &(*A)[i][j]);
    for (i = 0; i < *n; i++)
        for (j = 0; j < *n; j++)
            fscanf(ip, "%d\t", &(*B)[i][j]);
    fclose(ip);
    return 0;
}

/**
 * Save output data
 *
 * @param C Pointer to result matrix
 * @param n pointer to matrix size
 * @param Time calculation runtime
* @return Error code, 0 for OK, anything otherwise
 */
int SaveOutput(int **C, int *n, double time) {

    FILE *op;
    int i, j;

    if ((op = fopen("data_output", "w")) == NULL) {
        printf("Error opening the output file.\n");
        return 1;
    }

    fprintf(op, "%d\n\n", *n);
    for (i = 0; i < *n; i++) {
        for (j = 0; j < *n; j++)
            fprintf(op, "%d\t", C[i][j]);
        fprintf(op, "\n");
    }
    fprintf(op, "%f\n", time);
    fclose(op);
    return 0;
}
